//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.FindUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FindUser.IFindUser")]
    public interface IFindUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFindUser/findUser", ReplyAction="http://tempuri.org/IFindUser/findUserResponse")]
        CbuPortal.Entity.Models.tblFoundUsers[] findUser(string userInf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFindUser/findUser", ReplyAction="http://tempuri.org/IFindUser/findUserResponse")]
        System.Threading.Tasks.Task<CbuPortal.Entity.Models.tblFoundUsers[]> findUserAsync(string userInf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFindUser/getUser", ReplyAction="http://tempuri.org/IFindUser/getUserResponse")]
        CbuPortal.Entity.Models.tblUser getUser(string CurrentUser, string SelectedUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFindUser/getUser", ReplyAction="http://tempuri.org/IFindUser/getUserResponse")]
        System.Threading.Tasks.Task<CbuPortal.Entity.Models.tblUser> getUserAsync(string CurrentUser, string SelectedUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFindUserChannel : CbuPortal.FindUser.IFindUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindUserClient : System.ServiceModel.ClientBase<CbuPortal.FindUser.IFindUser>, CbuPortal.FindUser.IFindUser {
        
        public FindUserClient() {
        }
        
        public FindUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FindUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FindUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FindUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CbuPortal.Entity.Models.tblFoundUsers[] findUser(string userInf) {
            return base.Channel.findUser(userInf);
        }
        
        public System.Threading.Tasks.Task<CbuPortal.Entity.Models.tblFoundUsers[]> findUserAsync(string userInf) {
            return base.Channel.findUserAsync(userInf);
        }
        
        public CbuPortal.Entity.Models.tblUser getUser(string CurrentUser, string SelectedUser) {
            return base.Channel.getUser(CurrentUser, SelectedUser);
        }
        
        public System.Threading.Tasks.Task<CbuPortal.Entity.Models.tblUser> getUserAsync(string CurrentUser, string SelectedUser) {
            return base.Channel.getUserAsync(CurrentUser, SelectedUser);
        }
    }
}
