//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.ShareEventsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShareEventsService.IShareEvents")]
    public interface IShareEvents {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/shareComment", ReplyAction="http://tempuri.org/IShareEvents/shareCommentResponse")]
        bool shareComment(CbuPortal.Entity.Models.tblSharesComment userComment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/shareComment", ReplyAction="http://tempuri.org/IShareEvents/shareCommentResponse")]
        System.Threading.Tasks.Task<bool> shareCommentAsync(CbuPortal.Entity.Models.tblSharesComment userComment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/shareLike", ReplyAction="http://tempuri.org/IShareEvents/shareLikeResponse")]
        bool shareLike([System.ServiceModel.MessageParameterAttribute(Name="shareLike")] CbuPortal.Entity.Models.tblSharesLike shareLike1, bool shareLikeStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/shareLike", ReplyAction="http://tempuri.org/IShareEvents/shareLikeResponse")]
        System.Threading.Tasks.Task<bool> shareLikeAsync(CbuPortal.Entity.Models.tblSharesLike shareLike, bool shareLikeStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/setShare", ReplyAction="http://tempuri.org/IShareEvents/setShareResponse")]
        string setShare(CbuPortal.Entity.Models.tblShare share);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/setShare", ReplyAction="http://tempuri.org/IShareEvents/setShareResponse")]
        System.Threading.Tasks.Task<string> setShareAsync(CbuPortal.Entity.Models.tblShare share);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/getUserShares", ReplyAction="http://tempuri.org/IShareEvents/getUserSharesResponse")]
        WcfService1.tblShareInformation[] getUserShares(MongoDB.Bson.ObjectId userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/getUserShares", ReplyAction="http://tempuri.org/IShareEvents/getUserSharesResponse")]
        System.Threading.Tasks.Task<WcfService1.tblShareInformation[]> getUserSharesAsync(MongoDB.Bson.ObjectId userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/getFriendsShares", ReplyAction="http://tempuri.org/IShareEvents/getFriendsSharesResponse")]
        WcfService1.tblShareInformation[] getFriendsShares(MongoDB.Bson.ObjectId userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareEvents/getFriendsShares", ReplyAction="http://tempuri.org/IShareEvents/getFriendsSharesResponse")]
        System.Threading.Tasks.Task<WcfService1.tblShareInformation[]> getFriendsSharesAsync(MongoDB.Bson.ObjectId userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShareEventsChannel : CbuPortal.ShareEventsService.IShareEvents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShareEventsClient : System.ServiceModel.ClientBase<CbuPortal.ShareEventsService.IShareEvents>, CbuPortal.ShareEventsService.IShareEvents {
        
        public ShareEventsClient() {
        }
        
        public ShareEventsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShareEventsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShareEventsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShareEventsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool shareComment(CbuPortal.Entity.Models.tblSharesComment userComment) {
            return base.Channel.shareComment(userComment);
        }
        
        public System.Threading.Tasks.Task<bool> shareCommentAsync(CbuPortal.Entity.Models.tblSharesComment userComment) {
            return base.Channel.shareCommentAsync(userComment);
        }
        
        public bool shareLike(CbuPortal.Entity.Models.tblSharesLike shareLike1, bool shareLikeStatus) {
            return base.Channel.shareLike(shareLike1, shareLikeStatus);
        }
        
        public System.Threading.Tasks.Task<bool> shareLikeAsync(CbuPortal.Entity.Models.tblSharesLike shareLike, bool shareLikeStatus) {
            return base.Channel.shareLikeAsync(shareLike, shareLikeStatus);
        }
        
        public string setShare(CbuPortal.Entity.Models.tblShare share) {
            return base.Channel.setShare(share);
        }
        
        public System.Threading.Tasks.Task<string> setShareAsync(CbuPortal.Entity.Models.tblShare share) {
            return base.Channel.setShareAsync(share);
        }
        
        public WcfService1.tblShareInformation[] getUserShares(MongoDB.Bson.ObjectId userID) {
            return base.Channel.getUserShares(userID);
        }
        
        public System.Threading.Tasks.Task<WcfService1.tblShareInformation[]> getUserSharesAsync(MongoDB.Bson.ObjectId userID) {
            return base.Channel.getUserSharesAsync(userID);
        }
        
        public WcfService1.tblShareInformation[] getFriendsShares(MongoDB.Bson.ObjectId userID) {
            return base.Channel.getFriendsShares(userID);
        }
        
        public System.Threading.Tasks.Task<WcfService1.tblShareInformation[]> getFriendsSharesAsync(MongoDB.Bson.ObjectId userID) {
            return base.Channel.getFriendsSharesAsync(userID);
        }
    }
}
