//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccount")]
    public interface IAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/createUser", ReplyAction="http://tempuri.org/IAccount/createUserResponse")]
        CbuPortal.Entity.Models.tblLoginInformations createUser(CbuPortal.Entity.Models.tblUser user, CbuPortal.Entity.Models.tblProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/createUser", ReplyAction="http://tempuri.org/IAccount/createUserResponse")]
        System.Threading.Tasks.Task<CbuPortal.Entity.Models.tblLoginInformations> createUserAsync(CbuPortal.Entity.Models.tblUser user, CbuPortal.Entity.Models.tblProfile userProfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountChannel : CbuPortal.AccountService.IAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountClient : System.ServiceModel.ClientBase<CbuPortal.AccountService.IAccount>, CbuPortal.AccountService.IAccount {
        
        public AccountClient() {
        }
        
        public AccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CbuPortal.Entity.Models.tblLoginInformations createUser(CbuPortal.Entity.Models.tblUser user, CbuPortal.Entity.Models.tblProfile userProfile) {
            return base.Channel.createUser(user, userProfile);
        }
        
        public System.Threading.Tasks.Task<CbuPortal.Entity.Models.tblLoginInformations> createUserAsync(CbuPortal.Entity.Models.tblUser user, CbuPortal.Entity.Models.tblProfile userProfile) {
            return base.Channel.createUserAsync(user, userProfile);
        }
    }
}
